/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TELAS;

import MODEL.Bdproj;
import java.awt.Desktop;
import java.net.URL;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author lucas
 */
public class TelaCadastroProj extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroProj
     */
    public TelaCadastroProj() {

        initComponents();
        lbl_preencha.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_cancelar1 = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        btn_voltar1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_nomeproj = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_donoproj = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_ods = new javax.swing.JTextField();
        txt_descproj = new javax.swing.JTextField();
        btn_link = new javax.swing.JButton();
        txt_data = new javax.swing.JFormattedTextField();
        lbl_preencha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRO DE PROJETO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 17, 300, 60));

        btn_cancelar1.setText("Cancelar");
        btn_cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 245, 140, 50));

        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 245, 150, 50));

        btn_voltar1.setText("Voltar");
        btn_voltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 245, 140, 50));

        jLabel2.setText("Nome do Projeto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 61, -1, -1));

        jLabel6.setText("Descrição");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));
        getContentPane().add(txt_nomeproj, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 83, 229, 33));

        jLabel3.setText("Usuario do Dono");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));
        getContentPane().add(txt_donoproj, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 83, 221, 33));

        jLabel4.setText("Data de Criação");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 131, -1, -1));

        jLabel5.setText("Número da ODS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 131, -1, -1));

        txt_ods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_odsActionPerformed(evt);
            }
        });
        getContentPane().add(txt_ods, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 128, 121, -1));
        getContentPane().add(txt_descproj, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 185, 494, 54));

        btn_link.setText("Não sabe qual ODS usar? Clique aqui!");
        btn_link.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_linkActionPerformed(evt);
            }
        });
        getContentPane().add(btn_link, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 156, -1, -1));
        getContentPane().add(txt_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 128, 128, -1));

        lbl_preencha.setForeground(new java.awt.Color(255, 0, 51));
        lbl_preencha.setText("Preencha todos os campos");
        getContentPane().add(lbl_preencha, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 163, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelar1ActionPerformed
        // TODO add your handling code here:
        txt_nomeproj.setText("");
        txt_donoproj.setText("");
        txt_data.setText("");
        txt_ods.setText("");
        txt_descproj.setText("");
    }//GEN-LAST:event_btn_cancelar1ActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        // TODO add your handling code here:
        String cadastroNomeproj = txt_nomeproj.getText();
        String cadastroDonoproj = txt_donoproj.getText();
        String cadastroData = txt_data.getText();
        String cadastroOds = txt_ods.getText();
        String cadastroDescproj = txt_descproj.getText();

        Bdproj cadastroproj = new Bdproj(0, cadastroNomeproj, cadastroDonoproj, cadastroData, cadastroOds, cadastroDescproj);
        if (cadastroNomeproj.isEmpty() || cadastroDonoproj.isEmpty() || cadastroData.isEmpty() || cadastroOds.isEmpty() || cadastroDescproj.isEmpty()) {
            lbl_preencha.setVisible(true);
        } else {
            if (cadastroproj.Cadastrarproj()) {

                JOptionPane.showMessageDialog(null, "Projeto Cadastrado com Sucesso!");
                TelaMenu men = new TelaMenu();
                men.setVisible(true);
                men.pack();
                men.setLocationRelativeTo(null);
                men.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(null, "Erro no Cadastro");

            }
        }
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_voltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltar1ActionPerformed
        // TODO add your handling code here:
        TelaMenu men = new TelaMenu();
        men.setVisible(true);
        men.pack();
        men.setLocationRelativeTo(null);
        men.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btn_voltar1ActionPerformed

    private void btn_linkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_linkActionPerformed
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().browse(new URL("https://gtagenda2030.org.br/ods/").toURI());
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btn_linkActionPerformed

    private void txt_odsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_odsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_odsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroProj().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar1;
    private javax.swing.JButton btn_link;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JButton btn_voltar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbl_preencha;
    private javax.swing.JFormattedTextField txt_data;
    private javax.swing.JTextField txt_descproj;
    private javax.swing.JTextField txt_donoproj;
    private javax.swing.JTextField txt_nomeproj;
    private javax.swing.JTextField txt_ods;
    // End of variables declaration//GEN-END:variables
}
