/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TELAS;


import DAO.ConnectionFactory.ConnectionFactory;
import DAO.ConnectionFactory.ConsutausuarioDAO;
import com.mysql.jdbc.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import MODEL.Tusuario;
import com.mysql.jdbc.Connection;
import java.awt.event.ActionEvent;

/**
 *
 * @author lucas
 */
public class TelaAnaliseUsuario extends javax.swing.JFrame {

    /**
     * Creates new form TelaAnaliseUsuario
     */
    public TelaAnaliseUsuario() {
        initComponents();
        lbl_ctz.setVisible(false);
        btn_ctzex.setVisible(false);
        txt_nome.setEnabled(false);
        txt_usuario.setEnabled(false);
        txt_email.setEnabled(false);
        txt_num.setEnabled(false);
        txt_end.setEnabled(false);
        txt_senha.setEnabled(false);
        btn_voltar.setVisible(false);
        btn_excluir.setEnabled(false);
        btn_salvar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_menu = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbl_nome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_end = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_senha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_salvar = new javax.swing.JButton();
        txt_nome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_consultausu = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_usuario = new javax.swing.JTextField();
        btn_excluir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btn_ctzex = new javax.swing.JButton();
        txt_num = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lbl_ctz = new javax.swing.JLabel();
        btn_consultar = new javax.swing.JButton();
        btn_alterar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_menu.setText("Menu");
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });
        getContentPane().add(btn_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        btn_voltar.setFont(new java.awt.Font("Yu Gothic Medium", 0, 10)); // NOI18N
        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 125, 36));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        jLabel1.setText("Digite seu Usuário:");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));
        getContentPane().add(lbl_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel2.setText("Nome");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        getContentPane().add(txt_end, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 200, -1));

        jLabel3.setText("Telefone");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));
        getContentPane().add(txt_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 200, -1));

        jLabel4.setText("Endereço");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));
        getContentPane().add(txt_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 200, -1));

        jLabel5.setText("Senha");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));

        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
        getContentPane().add(txt_consultausu, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 170, -1));
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 200, -1));
        getContentPane().add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 200, -1));

        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        jLabel7.setText("Usuário");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        btn_ctzex.setText("Sim");
        btn_ctzex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ctzexActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ctzex, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));
        getContentPane().add(txt_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 200, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic Medium", 0, 36)); // NOI18N
        jLabel8.setText("Analisar Usuário");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        lbl_ctz.setText("Tem certeza?");
        getContentPane().add(lbl_ctz, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        btn_consultar.setText("Consultar");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        btn_alterar.setText("Alterar");
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_alterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 90, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\lucas\\Downloads\\ssss.png")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\lucas\\Downloads\\plll.png")); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        // TODO add your handling code here:
        btn_voltar.setVisible(!btn_voltar.isVisible());
    }//GEN-LAST:event_btn_menuActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TelaMenu menu = new TelaMenu();
        menu.setVisible(true);
        menu.pack();
        menu.setLocationRelativeTo(null);
        menu.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
        // TODO add your handling code here:
        if (!txt_nome.isEnabled()) {
            txt_nome.setEnabled(true);
            txt_email.setEnabled(true);
            txt_num.setEnabled(true);
            txt_end.setEnabled(true);
            btn_salvar.setEnabled(true);
            btn_excluir.setEnabled(true);

        } else {
            txt_nome.setEnabled(false);
            txt_email.setEnabled(false);
            txt_num.setEnabled(false);
            txt_end.setEnabled(false);
            btn_salvar.setEnabled(false);
            btn_excluir.setEnabled(false);

        }


    }//GEN-LAST:event_btn_alterarActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        // TODO add your handling code here:

        updateData();
           

    }//GEN-LAST:event_btn_salvarActionPerformed

    private void updateData() {
        
        String nome = txt_nome.getText();
        String usuario = txt_usuario.getText();
        String senha = txt_senha.getText();
        String tel = txt_num.getText();
        String ender = txt_end.getText();
        String email = txt_email.getText();

        try (java.sql.Connection con = new ConnectionFactory().obtemConexao()) {
            String sql = "UPDATE usuariobda3 SET nome = ?, senha = ?, tel = ?, ender = ?, email = ? WHERE usuario = ?";
            java.sql.PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, nome);
            stmt.setString(2, senha);
            stmt.setString(3, tel);
            stmt.setString(4, ender);
            stmt.setString(5, email);
            stmt.setString(6, usuario);
            int rowsAffected = stmt.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Dados atualizados com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao atualizar dados.");
            }
        } catch(Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
        }
    }
    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        // TODO add your handling code here:
        String usuarioc = txt_consultausu.getText();
        ConsutausuarioDAO c = new ConsutausuarioDAO();
        Tusuario tusu = c.consultanome(usuarioc);

        if (tusu != null) {
            txt_nome.setText(tusu.getNome());
            txt_usuario.setText(usuarioc);
            txt_end.setText(tusu.getEnder());
            txt_num.setText(tusu.getTel());
            txt_email.setText(tusu.getEmail());
        } else {
            JOptionPane.showMessageDialog(null, "Usuário não encontrado!");
        }
    }//GEN-LAST:event_btn_consultarActionPerformed

    private void deleteUser() {
        String usuario = txt_usuario.getText();
        String senha = txt_senha.getText();

        if (usuario.isEmpty() || senha.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos.");
            return;
        }

        try (java.sql.Connection con = new ConnectionFactory().obtemConexao()) {
            String selectSql = "SELECT senha FROM usuariobda3 WHERE usuario = ?";
            java.sql.PreparedStatement selectStmt = con.prepareStatement(selectSql);
            selectStmt.setString(1, usuario);
            java.sql.ResultSet rs = selectStmt.executeQuery();

            if (rs.next()) {
                String senhaCorreta = rs.getString("senha");
                if (senha.equals(senhaCorreta)) {
                    String deleteSql = "DELETE FROM usuariobda3 WHERE usuario = ?";
                    java.sql.PreparedStatement deleteStmt = con.prepareStatement(deleteSql);
                    deleteStmt.setString(1, usuario);
                    int rowsAffected = deleteStmt.executeUpdate();

                    if (rowsAffected > 0) {
                        JOptionPane.showMessageDialog(this, "Usuário excluído com sucesso!");
                    } else {
                        JOptionPane.showMessageDialog(this, "Erro ao excluir usuário.");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Senha incorreta.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Usuário não encontrado.");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao excluir usuário: " + ex.getMessage());
        }
    }
    
    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Insira a senha");
        btn_ctzex.setVisible(true);
        txt_senha.setEnabled(true);
        lbl_ctz.setVisible(true);
        
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_ctzexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ctzexActionPerformed
        // TODO add your handling code here:
        deleteUser();
    }//GEN-LAST:event_btn_ctzexActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAnaliseUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAnaliseUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAnaliseUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAnaliseUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAnaliseUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_ctzex;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_menu;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_ctz;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JTextField txt_consultausu;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_end;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_num;
    private javax.swing.JTextField txt_senha;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
