package TELAS;

import DAO.ConnectionFactory.CadastrousuarioDAO;
import MODEL.Tusuario;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        setLocationRelativeTo(null);
        initComponents();
        lbl_preencha.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_nomec = new javax.swing.JTextField();
        txt_usuarioc = new javax.swing.JTextField();
        txt_emailc = new javax.swing.JTextField();
        txt_numc = new javax.swing.JTextField();
        txt_endc = new javax.swing.JTextField();
        txt_senhac = new javax.swing.JTextField();
        btn_voltar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        e = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        saa = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_preencha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRO DE USUÁRIO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 300, 60));

        txt_nomec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomecActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nomec, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 200, 40));
        getContentPane().add(txt_usuarioc, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 210, 40));
        getContentPane().add(txt_emailc, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 200, 40));
        getContentPane().add(txt_numc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 200, 40));

        txt_endc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_endcActionPerformed(evt);
            }
        });
        getContentPane().add(txt_endc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 200, 40));
        getContentPane().add(txt_senhac, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 210, 40));

        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 140, 50));

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 140, 50));

        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 150, 50));

        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        jLabel3.setText("Crie uma Senha");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        jLabel4.setText("Nome");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        e.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        e.setText("Usuário");
        getContentPane().add(e, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        jLabel6.setText("Telefone");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        saa.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        saa.setText("Email");
        getContentPane().add(saa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        jLabel8.setText("Endereço");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        lbl_preencha.setForeground(new java.awt.Color(255, 0, 51));
        lbl_preencha.setText("Preencha todos os campos.");
        getContentPane().add(lbl_preencha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        // TODO add your handling code here:
        TelaLogin log = new TelaLogin();
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
        log.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        txt_endc.setText("");
        txt_emailc.setText("");
        txt_numc.setText("");
        txt_nomec.setText("");
        txt_senhac.setText("");
        txt_usuarioc.setText("");
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        // TODO add your handling code here:
        String cadastroLogin = txt_usuarioc.getText();
        String cadastroNome = txt_nomec.getText();
        String cadastroEmail = txt_emailc.getText();
        String cadastroNum = txt_numc.getText();
        String cadastroEnd = txt_endc.getText();
        String cadastroSenha = txt_senhac.getText();

        Tusuario cadastrousu = new Tusuario(cadastroLogin, cadastroSenha, cadastroEnd, cadastroNum, cadastroEmail, cadastroNome);
        if (cadastroLogin.isEmpty() || cadastroSenha.isEmpty() || cadastroEnd.isEmpty() || cadastroNum.isEmpty() || cadastroEmail.isEmpty() || cadastroNome.isEmpty()) {
            lbl_preencha.setVisible(true);
        } else {
            if (cadastrousu.Cadastrar()) {
                JOptionPane.showMessageDialog(null, "Lembre-se de salvar seu usuário e sua senha!\n Eles não poderão ser trocados!");
                JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso!");
                TelaLogin loginn = new TelaLogin();
                loginn.setVisible(true);
                loginn.pack();
                loginn.setLocationRelativeTo(null);
                loginn.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

            } else {
                JOptionPane.showMessageDialog(null, "Erro no Cadastro!");

            }
        }
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void txt_nomecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomecActionPerformed

    private void txt_endcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_endcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_endcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel e;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbl_preencha;
    private javax.swing.JLabel saa;
    private javax.swing.JTextField txt_emailc;
    private javax.swing.JTextField txt_endc;
    private javax.swing.JTextField txt_nomec;
    private javax.swing.JTextField txt_numc;
    private javax.swing.JTextField txt_senhac;
    private javax.swing.JTextField txt_usuarioc;
    // End of variables declaration//GEN-END:variables
}
